<Project>
  <PropertyGroup>
    <ProductVersion>6.0.0</ProductVersion>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="bblanchon.PDFium.Android" Version="156.0.8066" />
    <PackageVersion Include="bblanchon.PDFium.iOS" Version="156.0.8066" />
    <PackageVersion Include="bblanchon.PDFium.Linux" Version="156.0.8066" />
    <PackageVersion Include="bblanchon.PDFium.MacCatalyst" Version="145.0.7630" />
    <PackageVersion Include="bblanchon.PDFium.macOS" Version="156.0.8066" />
    <PackageVersion Include="bblanchon.PDFium.Win32" Version="156.0.8066" />
    <PackageVersion Include="ByteSize" Version="2.1.2" />
    <PackageVersion Include="Markdig.Signed" Version="1.4.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="11.0.0-rc.1.26425.128" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="11.0.0-rc.1.26425.128" />
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="11.0.0-rc.1.26425.128" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="11.0.0-rc.1.26451.6" />
    <PackageVersion Include="Microsoft.Maui.Controls.Compatibility" Version="11.0.0-preview.5.26304.4" />
    <PackageVersion Include="Microsoft.Testing.Extensions.GitHubActionsReport" Version="2.4.1" />
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.335" />
    <PackageVersion Include="PatrickJahr.Blazor.FileHandling" Version="1.0.0" />
    <PackageVersion Include="PatrickJahr.Blazor.WebShare" Version="1.0.0" />
    <PackageVersion Include="PDFtoImage" Version="$(PdfToImageVersion)" />
    <PackageVersion Include="PolySharp" Version="1.16.0" />
    <PackageVersion Include="SkiaSharp" Version="4.152.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Android" Version="4.152.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.iOS" Version="4.152.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.152.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.MacCatalyst" Version="4.152.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.macOS" Version="4.152.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.WebAssembly" Version="4.152.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Win32" Version="4.152.1" />
    <PackageVersion Include="Sungaila.PDFium.BlazorWebAssembly" Version="156.0.8066.1" />
    <PackageVersion Include="System.Buffers" Version="4.6.1" />
    <PackageVersion Include="System.Memory" Version="4.6.3" />
  </ItemGroup>
</Project>